version: "3.9"

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://mongo:27017/rocketchat"
      MONGO_OPLOG_URL: "mongodb://mongo:27017/local"
      ROOT_URL: "http://localhost:3000"
      PORT: 3000
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: